title: "John Einfeldt"
description: "Finance & Math @ MIT"
url: "https://johneinfeldt.github.io"
baseurl: ""

theme: minimal-mistakes-jekyll

author:
  name: "John Einfeldt"
  avatar: "/images/profile.png"
  bio: "Finance & Math @ MIT"
  location: "Cambridge, MA"
  email: "johneinf@mit.edu"
  linkedin: "https://www.linkedin.com/in/john-niklas-einfeldt-19851b1bb/"

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"
